spring.application.name=server

jwt.issuer=auth-service
jwt.access-token-audience=address-service,mail-service
jwt.mail-service-audience=mail-service
jwt.service-token-expiration-seconds=120
jwt.private-key-path=classpath:keys/private/private-key.pem
jwt.public-key-path=classpath:keys/public/public-key.pem
jwt.access-token-expiration-seconds=900
jwt.refresh-token-expiration-seconds=604800
jwt.confirmation-token-expiration-seconds=86400

app.mail.confirmation-subject=Confirme seu cadastro
app.mail.confirmation-url-template=http://localhost:8081/mail/confirm?token={token}

mail-service.url=http://localhost:8081

