Include /etc/nginx/modsecurity.d/modsecurity.conf
Include /etc/nginx/modsecurity.d/setup.conf
Include /etc/nginx/modsecurity.d/owasp-crs/rules/*.conf

Include /etc/nginx/modsecurity/auth_server.conf
Include /etc/nginx/modsecurity/resurce_server.conf
