
SecRule REQUEST_URI "@rx ^/api/(persons|contacts|addresses)" \
    "id:20001,\
    phase:1,\
    deny,\
    status:405,\
    log,\
    msg:'HTTP method not allowed on resource server',\
    chain"
SecRule REQUEST_METHOD "!@rx ^(GET|POST|PUT|DELETE)$" ""

SecRule REQUEST_URI "@rx ^/api/(persons|contacts|addresses)" \
    "id:20002,\
    phase:1,\
    deny,\
    status:401,\
    log,\
    msg:'Malformed Authorization header on resource server',\
    chain"
SecRule &REQUEST_HEADERS:Authorization "@eq 1" "chain"
SecRule REQUEST_HEADERS:Authorization "!@rx ^(?i)Bearer\s+" ""
