spring.application.name=addres-service
server.port=8082

# URL do endpoint de chaves públicas JWKS do Auth Server
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json

# Validações adicionais de JWT no Resource Server
security.jwt.expected-issuer=auth-service
security.jwt.expected-audience=address-service
