server {
    listen 80;
    server_name localhost;

    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsecurity.d/modsecurity.conf;
    
    location / {
        proxy_pass http://api-gateway:8080;
    }
}