spring.application.name=service
server.port=8081

# JWT Resource Server config
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json
security.jwt.expected-issuer=auth-service
security.jwt.expected-audience=mail-service

# Configurações de Banco de Dados (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/mail_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Integração com o Auth Server
auth-server.url=http://localhost:8080
auth-server.api-key=super-secret-auth-api-key

# Configurações de SMTP do Spring Mail
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:2525}


